### ISSUE TITLE
Fail on 2.7

### ISSUE THREAD

**Issue by thibmaek** [jinnovation/dogesay#3]
Tried to run this with my MacBook and failed by executing `python dogesay.py "wow such test"`
Ran it in a Vagrant box with Python 2.7.3 and got the following errors:

```
Traceback (most recent call last):
  File "dogesay-py", line 46, in <module>
    doge_face_path = DOGE_FACE_PATHS["ascii" if args.ascii else "norm"]
AttributeError: 'Namespace' object has no attribute 'ascii'
```

**Comment by jinnovation** [comment]
Turns out that was a remnant of an old feature (ASCII doge face) that I decided to take out. Take another look; this should be fixed now.

(By which I mean I took that line out.)
